### ISSUE TITLE
Fix AlamedaRecommendation.spec resource units

### ISSUE THREAD

**Issue by tsungming** [containers-ai/alameda#372]
```
apiVersion: autoscaling.containers.ai/v1alpha1
kind: AlamedaRecommendation
...
spec:
  containers:
    - name: alameda-ai-engine
      resources:
        limits:
          cpu: 4m
          memory: '579079662'
        requests:
          cpu: 2m
          memory: '579079662'
```

1. cpu: 4m -> 4000m

1. need define the minimum cpu size, it should not be '0'.

1. memory: 579079662 -> 579Mi
