### ISSUE TITLE
[feature] add an enable flag in AlamedaScaler CRD to toggle execution

### ISSUE THREAD

**Issue by mamafun** [containers-ai/alameda#381]
`spec.enable = true` means enable **execution** for the pods selected in this alamedaScaler and vice versa

For example, the following AlamedaScaler CR will disable recommendation execution.
(But recommendation is still available and visible in Grafana GUI)

```
apiVersion: autoscaling.containers.ai/v1alpha1
kind: AlamedaScaler
metadata:
  name: ai
  namespace: test
spec:
  policy: compact
  enable: false
  selector:
    matchLabels:
      app: alameda
      component: alameda-ai
```
