### ISSUE TITLE
expand apiGroups in webhook configurations' rule 

### ISSUE THREAD

**Issue by rax845163** [containers-ai/alameda#420]
**Is your feature request related to a problem? Please describe.**

Alameda-Operator intercepts *create* and *update* events of kind *AlamedaScaler*, *Deployment* and *DeploymentConfig*.Each APIGroups that may reference to these kinds need to be intercept by alameda-operator.For example, not only does apiGroup *extension* needs to be intercept but also apiGroups *apps* needs while creating and updating Deployment. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mamafun** [comment]
Therefore in summary, Alameda watches _AlamedaScaler_, _Deployment_, and _DeploymentConfig for version:
- apps.v1
- apps.v1beta1
- apps.v1beta2
- extensions.v1beta1
?
@rax845163 am I right?

**Comment by rax845163** [comment]
@mamafun 
Yes, but we're using validation webhook server instead of mutation webhook server.
And we also validate requests below.
```
- apiGroups:
  - autoscaling.containers.ai
  apiVersions:
  - v1alpha1
  operations:
  - CREATE
  - UPDATE
  resources:
  - alamedascalers
```
