### ISSUE TITLE
Pod is selected by two controller in AlamedaScaler's status 

### ISSUE THREAD

**Issue by rax845163** [containers-ai/alameda#591]
**Describe the bug**

Pod shoud not be recorded in the AlamedaScaler.Stauts.Deployment which pod was not created by.
**To Reproduce**

1. Apply following yaml
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: webapp2
---
apiVersion: autoscaling.containers.ai/v1alpha1
kind: AlamedaScaler
metadata:
  name: alameda
  namespace: webapp2
spec:
  policy: stable
  enableExecution: true
  scalingTool:
    type: vpa
  selector:
    matchLabels:
      app: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
  namespace: webapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi 
      serviceAccount: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment2
  namespace: webapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi 
      serviceAccount: nginx 
```
2. $ kubectl -n webapp2 get alamedascaler alameda -o json | jq '.status'
**Expected behavior**

**Screenshots**

 
![Screen Shot 2019-06-27 at 12 00 21 PM](https://user-images.githubusercontent.com/2918565/60233511-35d23200-98d3-11e9-97ac-ea1ddd47952d.png)
![Screen Shot 2019-06-27 at 12 00 41 PM](https://user-images.githubusercontent.com/2918565/60233515-379bf580-98d3-11e9-9519-50b658922d5f.png)

**Environment:**

**Additional context**
